language: go
framework: echo
app_dir: apps/go/echo

endpoints:
  - name: json
    path: /json
  - name: db-single
    path: /db
  - name: db-multi
    path: /queries?queries=10
  - name: fortunes
    path: /fortunes

load:
  rps: 100
  duration: 60s
  warmup: 10s
  connections: 10

iterations: 10

resources:
  app:
    cpus: "2"
    memory: "512m"
  postgres:
    cpus: "1"
    memory: "256m"
